# Generated by Django 6.0 on 2025-12-22 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_kannada', models.TextField(help_text='Question in Kannada')),
                ('question_english', models.TextField(blank=True, help_text='English translation (optional)')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('category', models.CharField(choices=[('basic_syntax', 'Basic Syntax'), ('loops', 'Loops'), ('conditionals', 'Conditionals'), ('functions', 'Functions'), ('data_structures', 'Data Structures'), ('algorithms', 'Algorithms')], default='basic_syntax', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='CodeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kannada_input', models.TextField(help_text='Algorithm description in Kannada')),
                ('english_translation', models.TextField(blank=True, help_text='Auto-translated English version')),
                ('generated_python_code', models.TextField(blank=True)),
                ('code_output', models.TextField(blank=True, help_text='Program output or None if not executed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed', null=True)),
                ('error_kannada', models.TextField(blank=True, help_text='Error translated to Kannada', null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('is_valid', models.BooleanField(default=False, help_text='Whether code is syntactically valid')),
                ('use_trinket', models.BooleanField(default=False, help_text='Whether to use Trinket IO for execution')),
                ('trinket_embed_url', models.URLField(blank=True, null=True)),
                ('trinket_iframe_html', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('success', 'Success'), ('error', 'Error'), ('pending', 'Pending')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_session_time', models.IntegerField(default=0, help_text='Total time in minutes')),
                ('total_codes_executed', models.IntegerField(default=0)),
                ('successful_codes', models.IntegerField(default=0)),
                ('total_quiz_attempts', models.IntegerField(default=0)),
                ('total_quiz_correct', models.IntegerField(default=0)),
                ('quiz_accuracy', models.FloatField(default=0.0, help_text='Percentage accuracy')),
                ('strongest_category', models.CharField(blank=True, max_length=50)),
                ('weakest_category', models.CharField(blank=True, max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('days_active', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0, help_text='Current consecutive days active')),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('coding', 'Coding'), ('quiz', 'Quiz'), ('practice', 'Practice')], default='coding', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('codes_written', models.IntegerField(default=0)),
                ('quizzes_attempted', models.IntegerField(default=0)),
                ('quizzes_correct', models.IntegerField(default=0)),
                ('session_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text_kannada', models.TextField()),
                ('option_text_english', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation_kannada', models.TextField(blank=True, help_text="Why this is/isn't correct in Kannada")),
                ('explanation_english', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.quizquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('weak_area', 'Weak Area - Study This'), ('next_level', 'Next Level Challenge'), ('review', 'Review Previous Topic'), ('practice_more', 'Practice More on Topic')], default='weak_area', max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('recommendation_kannada', models.TextField()),
                ('recommendation_english', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0, help_text='1-10, higher = more important')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kannada_proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('preferred_language', models.CharField(choices=[('kn', 'Kannada'), ('en', 'English')], default='kn', max_length=10)),
                ('total_codes_written', models.IntegerField(default=0)),
                ('total_quizzes_attempted', models.IntegerField(default=0)),
                ('total_quizzes_passed', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.IntegerField(blank=True, help_text='Time taken in seconds', null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.quizoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.quizquestion')),
            ],
            options={
                'ordering': ['-attempted_at'],
                'unique_together': {('user', 'question', 'attempted_at')},
            },
        ),
    ]
